# Generated by Django 4.2.7 on 2025-09-23 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Commit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sha', models.CharField(max_length=40, unique=True)),
                ('message', models.TextField()),
                ('author_name', models.CharField(max_length=255)),
                ('author_email', models.CharField(max_length=255)),
                ('committer_name', models.CharField(max_length=255)),
                ('committer_email', models.CharField(max_length=255)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('total_changes', models.IntegerField(default=0)),
                ('files_changed', models.IntegerField(default=0)),
                ('commit_date', models.DateTimeField()),
                ('html_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Commit',
                'verbose_name_plural': 'Commits',
                'db_table': 'commits',
                'ordering': ['-commit_date'],
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('github_id', models.BigIntegerField(unique=True)),
                ('name', models.CharField(max_length=255)),
                ('full_name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('stars_count', models.IntegerField(default=0)),
                ('forks_count', models.IntegerField(default=0)),
                ('watchers_count', models.IntegerField(default=0)),
                ('size', models.IntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_fork', models.BooleanField(default=False)),
                ('is_archived', models.BooleanField(default=False)),
                ('html_url', models.URLField()),
                ('clone_url', models.URLField()),
                ('github_created_at', models.DateTimeField()),
                ('github_updated_at', models.DateTimeField()),
                ('github_pushed_at', models.DateTimeField(blank=True, null=True)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('syncing', 'Syncing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repositories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repository',
                'verbose_name_plural': 'Repositories',
                'db_table': 'repositories',
                'ordering': ['-github_updated_at'],
            },
        ),
        migrations.CreateModel(
            name='CommitFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=500)),
                ('status', models.CharField(choices=[('added', 'Added'), ('modified', 'Modified'), ('removed', 'Removed'), ('renamed', 'Renamed')], max_length=20)),
                ('additions', models.IntegerField(default=0)),
                ('deletions', models.IntegerField(default=0)),
                ('changes', models.IntegerField(default=0)),
                ('commit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='github.commit')),
            ],
            options={
                'verbose_name': 'Commit File',
                'verbose_name_plural': 'Commit Files',
                'db_table': 'commit_files',
            },
        ),
        migrations.AddField(
            model_name='commit',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commits', to='github.repository'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['user', 'name'], name='repositorie_user_id_f39b93_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['github_id'], name='repositorie_github__59aed5_idx'),
        ),
        migrations.AddIndex(
            model_name='repository',
            index=models.Index(fields=['sync_status'], name='repositorie_sync_st_1dd4c4_idx'),
        ),
        migrations.AddIndex(
            model_name='commitfile',
            index=models.Index(fields=['commit', 'filename'], name='commit_file_commit__3fcd77_idx'),
        ),
        migrations.AddIndex(
            model_name='commitfile',
            index=models.Index(fields=['status'], name='commit_file_status_6ba1b1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='commitfile',
            unique_together={('commit', 'filename')},
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['repository', 'commit_date'], name='commits_reposit_77e318_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['sha'], name='commits_sha_ae771e_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['author_name'], name='commits_author__69a0de_idx'),
        ),
        migrations.AddIndex(
            model_name='commit',
            index=models.Index(fields=['commit_date'], name='commits_commit__46291f_idx'),
        ),
    ]
