# Generated by Django 4.2.7 on 2025-09-23 01:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('performance', 'Performance Analysis'), ('quality', 'Code Quality'), ('productivity', 'Developer Productivity'), ('collaboration', 'Team Collaboration'), ('security', 'Security Analysis'), ('general', 'General Analysis')], max_length=20)),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='openai', max_length=20)),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('prompt_template', models.TextField()),
                ('max_tokens', models.IntegerField(default=2000)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_public', models.BooleanField(default=True)),
                ('usage_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Agent Template',
                'verbose_name_plural': 'Agent Templates',
                'db_table': 'agent_templates',
                'ordering': ['category', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('ai_provider', models.CharField(choices=[('openai', 'OpenAI'), ('anthropic', 'Anthropic (Claude)')], default='openai', max_length=20)),
                ('model_name', models.CharField(default='gpt-3.5-turbo', max_length=100)),
                ('prompt_template', models.TextField(help_text='Use placeholders like {developer_name}, {repository_name}, {commit_data}, {date_range}')),
                ('max_tokens', models.IntegerField(default=2000)),
                ('temperature', models.FloatField(default=0.7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'AI Agent',
                'verbose_name_plural': 'AI Agents',
                'db_table': 'ai_agents',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'name')},
            },
        ),
    ]
